name: password-wallet
services:
  frontend:
    image: ghcr.io/nilsharr/passwordwallet-frontend:latest
    ports:
      - "8000:443"
    volumes:
      - ./PasswordWallet.Client/cert/local:/cert
      - ./PasswordWallet.Client/nginx.conf:/etc/nginx/nginx.conf

  backend:
    image: ghcr.io/nilsharr/passwordwallet-backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ConnectionStrings:PasswordWalletConnection=Server=postgres;Port=5432;Database=PasswordWallet;User Id=postgres;Password=root;
      - CorsOptions:Origins__0=https://localhost:8000
    depends_on:
      - postgres
    restart: on-failure:5
    ports:
      - "7165:8080"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: PasswordWallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
 
volumes:
  postgres-data: