// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PasswordWallet.Server.Data;

#nullable disable

namespace PasswordWallet.Server.Data.Migrations
{
    [DbContext(typeof(PasswordWalletDbContext))]
    [Migration("20221213222829_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PasswordWallet.Server.Entities.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsPasswordKeptAsHash")
                        .HasColumnType("boolean")
                        .HasColumnName("is_password_kept_as_hash");

                    b.Property<DateTime?>("LockoutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_time");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("salt");

                    b.Property<int>("SubsequentBadLogins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("subsequent_bad_logins");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_account_login");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.AccountLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<bool>("Correct")
                        .HasColumnType("boolean")
                        .HasColumnName("correct");

                    b.Property<long>("LoginIpAddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("login_ip_address_id");

                    b.Property<DateTime>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_account_login");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_login_account_id");

                    b.HasIndex("LoginIpAddressId")
                        .HasDatabaseName("ix_account_login_login_ip_address_id");

                    b.ToTable("account_login", (string)null);
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.Credential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<string>("Login")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password");

                    b.Property<string>("WebAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("web_address");

                    b.HasKey("Id")
                        .HasName("pk_credential");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_credential_account_id");

                    b.ToTable("credential", (string)null);
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.LoginIpAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountOfBadLogins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("amount_of_bad_logins");

                    b.Property<long>("AmountOfGoodLogins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("amount_of_good_logins");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<bool>("PermanentLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permanent_lock");

                    b.Property<int>("SubsequentBadLogins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("subsequent_bad_logins");

                    b.Property<DateTime?>("TemporaryLock")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("temporary_lock");

                    b.HasKey("Id")
                        .HasName("pk_login_ip_address");

                    b.ToTable("login_ip_address", (string)null);
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.AccountLogin", b =>
                {
                    b.HasOne("PasswordWallet.Server.Entities.Account", "Account")
                        .WithMany("AccountLogin")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_login_account_account_id");

                    b.HasOne("PasswordWallet.Server.Entities.LoginIpAddress", "LoginIpAddress")
                        .WithMany("AccountLogins")
                        .HasForeignKey("LoginIpAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_login_login_ip_address_login_ip_address_id");

                    b.Navigation("Account");

                    b.Navigation("LoginIpAddress");
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.Credential", b =>
                {
                    b.HasOne("PasswordWallet.Server.Entities.Account", "Account")
                        .WithMany("Credentials")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credential_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.Account", b =>
                {
                    b.Navigation("AccountLogin");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("PasswordWallet.Server.Entities.LoginIpAddress", b =>
                {
                    b.Navigation("AccountLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
