name: Reusable docker image build

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      context:
        description: 'Docker build context'
        required: true
        type: string
      cache_repository:
        description: 'Docker cache registry'
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3   
      
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image_name }}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch,suffix=-{{ sha }}
          type=raw,value=latest,enable={{is_default_branch}}
            
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.cache_repository }}
        cache-to: type=registry,ref=${{ inputs.cache_repository  }},mode=max